name: Run Unit tests
description: Run unit tests on the codebase

inputs:
  with-coverage:
    description: 'Whether to run tests with coverage'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      shell: bash
      run: pip install poetry && poetry install
    - name: Run unit tests
      shell: bash
      run: | 
        if [ "${{ inputs.with-coverage }}" = "true" ]; then
          poetry run pytest --cov .
        else
          poetry run pytest
        fi